@echo off
setlocal
set OUTDIR=g:\matrix\screenshots
set EDGE="C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
if not exist "%OUTDIR%" mkdir "%OUTDIR%"

echo.
echo ========================================
echo   MATRIX COMPREHENSIVE UI CAPTURE
echo ========================================
echo.

echo === NEXUS (port 3001) ===
echo   Capturing nexus_01_dashboard...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\nexus_01_dashboard.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3001" 2>nul
echo   Capturing nexus_02_analytics...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\nexus_02_analytics.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3001/analytics" 2>nul
echo   Capturing nexus_03_diagnostics...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\nexus_03_diagnostics.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3001/diagnostics" 2>nul
echo   Capturing nexus_04_integrations...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\nexus_04_integrations.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3001/integrations" 2>nul
echo   Capturing nexus_05_knowledge...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\nexus_05_knowledge.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3001/knowledge" 2>nul
echo   Capturing nexus_06_settings...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\nexus_06_settings.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3001/settings" 2>nul

echo.
echo === REFLECT (port 3000) ===
echo   Capturing reflect_01_landing...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_01_landing.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000" 2>nul
echo   Capturing reflect_02_login...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_02_login.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/login" 2>nul
echo   Capturing reflect_03_auth...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_03_auth.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/auth" 2>nul
echo   Capturing reflect_04_setup...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_04_setup.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/setup" 2>nul
echo   Capturing reflect_05_setup_initial...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_05_setup_initial.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/setup/initial" 2>nul
echo   Capturing reflect_06_neural_init...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_06_neural_init.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/neural-initialize" 2>nul
echo   Capturing reflect_07_onboarding...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_07_onboarding.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/onboarding" 2>nul
echo   Capturing reflect_08_tutorial...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_08_tutorial.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/tutorial" 2>nul
echo   Capturing reflect_09_session...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_09_session.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/session" 2>nul
echo   Capturing reflect_10_dashboard_loading...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_10_dashboard_loading.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/dashboard-loading" 2>nul
echo   Capturing reflect_11_journal...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_11_journal.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/journal" 2>nul
echo   Capturing reflect_12_archive...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_12_archive.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/archive" 2>nul
echo   Capturing reflect_13_capsule...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_13_capsule.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/capsule" 2>nul
echo   Capturing reflect_14_growth...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_14_growth.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/growth" 2>nul
echo   Capturing reflect_15_insights...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_15_insights.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/insights" 2>nul
echo   Capturing reflect_16_patterns...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_16_patterns.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/patterns" 2>nul
echo   Capturing reflect_17_graph...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_17_graph.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/graph" 2>nul
echo   Capturing reflect_18_paths...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_18_paths.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/paths" 2>nul
echo   Capturing reflect_19_search...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_19_search.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/search" 2>nul
echo   Capturing reflect_20_sage...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_20_sage.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/sage" 2>nul
echo   Capturing reflect_21_chat...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_21_chat.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/chat" 2>nul
echo   Capturing reflect_22_voice...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_22_voice.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/voice" 2>nul
echo   Capturing reflect_23_profile...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_23_profile.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/profile" 2>nul
echo   Capturing reflect_24_settings...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_24_settings.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/settings" 2>nul
echo   Capturing reflect_25_settings_dev...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_25_settings_dev.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/settings/developer" 2>nul
echo   Capturing reflect_26_system...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_26_system.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/system" 2>nul
echo   Capturing reflect_27_debug...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_27_debug.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/debug" 2>nul
echo   Capturing reflect_28_demo...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_28_demo.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/demo" 2>nul
echo   Capturing reflect_29_common...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_29_common.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/common" 2>nul
echo   Capturing reflect_30_trash...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\reflect_30_trash.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:3000/trash" 2>nul

echo.
echo === GHOST COMMAND (port 5173) ===
echo   Capturing ghost_01_dashboard...
%EDGE% --headless=new --disable-gpu --screenshot="%OUTDIR%\ghost_01_dashboard.png" --window-size=430,932 --hide-scrollbars --force-device-scale-factor=3 --virtual-time-budget=10000 --run-all-compositor-stages-before-draw "http://localhost:5173" 2>nul

echo.
echo ========================================
echo   CAPTURE COMPLETE
echo   Output: %OUTDIR%
echo ========================================
dir /b "%OUTDIR%\*.png" 2>nul | find /c /v "" 
echo screenshots captured.
