/**
 * RALPH CORE (Recursive Autonomous Loop for Programming Heuristics)
 * Shared Agent Logic for CLI and Sentinel
 * 
 * v3.0 — PRD-driven loop engine with Sage environment checks
 */

import { Sage } from './engine.mjs';
import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import util from 'util';

const execAsync = util.promisify(exec);
const sage = new Sage();

export class RalphCore {
    constructor(workingDir = process.cwd()) {
        this.workingDir = workingDir;
        this.history = [];
        this.maxRetries = 3;
        this.currentTask = null;
        this.prdPath = null;
        this.progressPath = null;
    }

    /**
     * Load a PRD file and extract the task checklist
     */
    parsePRD(prdContent) {
        const tasks = [];
        const lines = prdContent.split('\n');
        for (const line of lines) {
            const unchecked = line.match(/^- \[ \] \*\*(.+?)\*\* — (.+)$/);
            const checked = line.match(/^- \[x\] \*\*(.+?)\*\* — (.+)$/i);
            if (unchecked) {
                tasks.push({ id: unchecked[1], description: unchecked[2], done: false });
            } else if (checked) {
                tasks.push({ id: checked[1], description: checked[2], done: true });
            }
        }
        return tasks;
    }

    /**
     * Find the next unchecked task in the PRD
     */
    getNextTask(prdContent) {
        const tasks = this.parsePRD(prdContent);
        return tasks.find(t => !t.done) || null;
    }

    /**
     * Mark a task as complete in the PRD file
     */
    markTaskComplete(prdContent, taskId) {
        return prdContent.replace(
            new RegExp(`^- \\[ \\] \\*\\*${taskId.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\*\\*`, 'm'),
            `- [x] **${taskId}**`
        );
    }

    /**
     * Update or create a progress file
     */
    updateProgress(taskId, status, attempt, notes, commitHash = '') {
        if (!this.progressPath) return;
        const now = new Date().toISOString();
        let content = '';
        try {
            content = fs.readFileSync(this.progressPath, 'utf8');
        } catch {
            content = `# Progress Log\n\n> Auto-generated by Ralph Loop\n> Started: ${now}\n\n## Iteration Log\n\n`;
        }
        const entry = `### ${taskId} — ${now}\n- **Status:** ${status}\n- **Attempt:** ${attempt}\n- **Notes:** ${notes}\n${commitHash ? `- **Commit:** ${commitHash}\n` : ''}\n`;
        content += entry;
        fs.writeFileSync(this.progressPath, content);
    }

    /**
     * Run the full PRD-driven loop
     * This is Ralph's main event — feed tasks one at a time until COMPLETE
     */
    async runPRDLoop(prdFilePath, options = {}) {
        this.prdPath = path.resolve(this.workingDir, prdFilePath);
        const prdDir = path.dirname(this.prdPath);
        const prdName = path.basename(this.prdPath, '.md');
        this.progressPath = path.resolve(prdDir, 'progress', `${prdName}_progress.md`);
        fs.mkdirSync(path.dirname(this.progressPath), { recursive: true });

        const log = options.log || console.log;
        log(`\x1b[36m[RALPH] PRD Loop started: ${this.prdPath}\x1b[0m`);

        let loopCount = 0;
        const maxLoops = options.maxLoops || 100;

        while (loopCount < maxLoops) {
            loopCount++;
            let prdContent;
            try {
                prdContent = fs.readFileSync(this.prdPath, 'utf8');
            } catch (e) {
                log(`\x1b[31m[RALPH] Cannot read PRD: ${e.message}\x1b[0m`);
                return { success: false, error: 'PRD file not found' };
            }

            const task = this.getNextTask(prdContent);
            if (!task) {
                log(`\x1b[32m[RALPH] All tasks complete! <promise>COMPLETE</promise>\x1b[0m`);
                this.updateProgress('ALL', '✅ COMPLETE', loopCount, 'All PRD tasks passed');
                return { success: true, loops: loopCount };
            }

            log(`\n\x1b[35m[RALPH] Task ${task.id}: ${task.description}\x1b[0m`);
            this.currentTask = task;

            let attempts = 0;
            let taskDone = false;

            while (attempts < this.maxRetries && !taskDone) {
                attempts++;
                log(`\x1b[90m[RALPH] Attempt ${attempts}/${this.maxRetries}\x1b[0m`);

                // Reset history for each task to keep context window clean
                this.history = [];

                try {
                    const plan = await this.think(
                        `You are working through a PRD. Your current task:\n` +
                        `**${task.id}**: ${task.description}\n\n` +
                        `Working directory: ${this.workingDir}\n` +
                        `Complete this specific task. When done, use the COMPLETE tool.`
                    );

                    if (plan.tool === 'COMPLETE') {
                        taskDone = true;
                        break;
                    }

                    // Execute the planned action
                    const { done, result } = await this.execute(plan.tool, plan.args, log);
                    if (done) {
                        taskDone = true;
                        break;
                    }

                    // Let Ralph keep thinking until COMPLETE or max iterations
                    let innerLoop = 0;
                    while (!taskDone && innerLoop < 20) {
                        innerLoop++;
                        const nextPlan = await this.think(
                            `Continue working on task **${task.id}**: ${task.description}\n` +
                            `Last result: ${result?.substring(0, 500)}`
                        );
                        if (nextPlan.tool === 'COMPLETE') {
                            taskDone = true;
                            break;
                        }
                        const next = await this.execute(nextPlan.tool, nextPlan.args, log);
                        if (next.done) {
                            taskDone = true;
                            break;
                        }
                    }
                } catch (e) {
                    log(`\x1b[31m[RALPH] Error on attempt ${attempts}: ${e.message}\x1b[0m`);
                    this.updateProgress(task.id, `❌ Error attempt ${attempts}`, attempts, e.message);
                }
            }

            if (taskDone) {
                // Mark in PRD
                prdContent = fs.readFileSync(this.prdPath, 'utf8');
                const updated = this.markTaskComplete(prdContent, task.id);
                fs.writeFileSync(this.prdPath, updated);
                this.updateProgress(task.id, '✅ Complete', attempts, 'Task passed');
                log(`\x1b[32m[RALPH] ✓ Task ${task.id} complete\x1b[0m`);
            } else {
                log(`\x1b[31m[RALPH] ✗ Task ${task.id} failed after ${this.maxRetries} attempts. Escalating.\x1b[0m`);
                this.updateProgress(task.id, '❌ ESCALATED', attempts, `Failed after ${this.maxRetries} retries`);
                return { success: false, failedTask: task.id, loops: loopCount };
            }
        }

        log(`\x1b[33m[RALPH] Max loop count reached (${maxLoops})\x1b[0m`);
        return { success: false, error: 'Max loops exceeded', loops: loopCount };
    }

    async think(goal, options = {}) {
        const systemPrompt = `
You are RALPH (Recursive Autonomous Loop for Programming Heuristics).
Your goal is to complete the user's request by autonomously executing tools.
You have access to the file system and command line.

TOOLS:
1. LIST_DIR(path) - List files in a directory.
2. READ_FILE(path) - Read file content.
3. WRITE_FILE(path, content) - Create or overwrite a file.
4. EXECUTE(command) - Run a shell command.
5. SEARCH_FILES(term, dir) - Search for a string in files (Recursive).
6. MEMORY(text) - Save a thought or observation to your memory.
6. COMPLETE(result) - Signal that the task is finished.

RESPONSE FORMAT:
You MUST respond with valid JSON only.
{
    "thought": "Analysis of the current state and plan...",
    "tool": "TOOL_NAME",
    "args": ["arg1", "arg2"]
}
`;

        // Initial Context
        if (this.history.length === 0) {
            this.history.push({ role: 'system', content: systemPrompt });
            this.history.push({ role: 'user', content: `GOAL: ${goal}` });
        } else {
            this.history.push({ role: 'user', content: `GOAL: ${goal}` });
        }

        try {
            const response = await sage.json(this.history, null, { temperature: 0.2 });
            return response;
        } catch (error) {
            console.error('[RALPH] Thinking Error:', error);
            return { thought: "Error during thought process.", tool: "COMPLETE", args: ["Failed to think."] };
        }
    }

    async execute(tool, args, logCallback = console.log) {
        logCallback(`[RALPH] Tool: ${tool} ${JSON.stringify(args)}`);

        let result = '';

        try {
            switch (tool) {
                case 'LIST_DIR':
                    const dirPath = path.resolve(this.workingDir, args[0] || '.');
                    const files = fs.readdirSync(dirPath);
                    result = `Files in ${dirPath}:\n${files.join('\n')}`;
                    break;

                case 'READ_FILE':
                    const filePath = path.resolve(this.workingDir, args[0]);
                    result = fs.readFileSync(filePath, 'utf8');
                    break;

                case 'WRITE_FILE':
                    const writePath = path.resolve(this.workingDir, args[0]);
                    fs.mkdirSync(path.dirname(writePath), { recursive: true });
                    fs.writeFileSync(writePath, args[1]);
                    result = `Wrote ${args[1].length} bytes to ${writePath}`;
                    break;

                case 'EXECUTE':
                    const { stdout, stderr } = await execAsync(args[0], { cwd: this.workingDir });
                    result = stdout + (stderr ? `\nSTDERR: ${stderr}` : '');
                    break;

                case 'SEARCH_FILES':
                    const term = args[0];
                    const searchDir = args[1] || '.';
                    // Use grep (Linux/Mac) or findstr (Windows)
                    // Since we are on Windows (Matrix), we use findstr /s /i /n "term" *
                    // But 'grep' is often available in git bash. Let's try native findstr for safety or a simple JS recursive search if node.
                    // Actually, let's use a pure Node implementation to be cross-platform safe and avoid shell quoting hell.

                    const getAllFiles = (dir, fileList = []) => {
                        const files = fs.readdirSync(dir);
                        files.forEach(file => {
                            if (file.startsWith('node_modules') || file.startsWith('.git')) return;
                            const filePath = path.join(dir, file);
                            const stat = fs.statSync(filePath);
                            if (stat.isDirectory()) {
                                getAllFiles(filePath, fileList);
                            } else {
                                fileList.push(filePath);
                            }
                        });
                        return fileList;
                    };

                    const allFiles = getAllFiles(path.resolve(this.workingDir, searchDir));
                    const matches = [];
                    allFiles.forEach(f => {
                        try {
                            const content = fs.readFileSync(f, 'utf8');
                            const lines = content.split('\n');
                            lines.forEach((line, i) => {
                                if (line.includes(term)) {
                                    matches.push(`${path.relative(this.workingDir, f)}:${i + 1}: ${line.trim().substring(0, 100)}`);
                                }
                            });
                        } catch (e) { } // Binary files etc
                    });

                    result = matches.length > 0 ? matches.slice(0, 20).join('\n') + (matches.length > 20 ? `\n...and ${matches.length - 20} more.` : '') : 'No matches found.';
                    break;

                case 'MEMORY':
                    result = `Memory stored: ${args[0]}`;
                    break;

                case 'COMPLETE':
                    return { done: true, result: args[0] };

                default:
                    result = `Unknown tool: ${tool}`;
            }
        } catch (error) {
            result = `Error executing ${tool}: ${error.message}`;
        }

        // Feed result back into history
        this.history.push({ role: 'assistant', content: JSON.stringify({ tool, args }) });
        this.history.push({ role: 'user', content: `TOOL_OUTPUT: ${result}` });

        return { done: false, result };
    }
}
